### ISSUE TITLE
Can't parse files that use async iterators

### ISSUE THREAD

**Issue by basicdays** [esdoc/esdoc-es7-plugin#11]
ESDoc currently isn't able to parse files that use Babel async-iterator plugin found here: https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-async-generator-functions

The spec can be found here: https://github.com/tc39/proposal-async-iteration

I would imagine issue #9 would solve this issue.

**Comment by h13i32maru** [comment]
Sorry for late reply.
This plugin is out-of-date. Please check [using ECMAScript Proposal](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
