### ISSUE TITLE
What needs to be done to handle ES7 properly?

### ISSUE THREAD

**Issue by madx** [esdoc/esdoc-es7-plugin#2]
Hi,

I started using `esdoc` for an ES6/7 project and I would like to know what needs to be done so we can go from:

```
This plugin only ignores ES7 syntax(does not optimize) to produce the documentation. So, ES7 information(ClassProperties, AsyncFunctions and etc...) is not presented in the documentation.
```

to

```
This plugin adds ES7 experimental syntax support to esdoc in order to have ES7 information (ClassProperties, AsyncFunctions and etc...) presented in the documentation.
```

:smile:

**Comment by h13i32maru** [comment]
@madx Hi! Thanks for this question!

In order to go there, needs two condition.
1. Each ES7 features will be stage2(babel default)
2. ESDoc will be stable(currently has some bug)

Thanks.
