### ISSUE TITLE
Can we treat async functions as normal?

### ISSUE THREAD

**Issue by RobinQu** [esdoc/esdoc-es7-plugin#5]
Most part of my documentation is lost because of ignoring async functions.

I suppose we can treat async function as normal function just right now.

**Comment by balmasi** [comment]
+1 , but do you see any reason why we should NOT treat it like a normal function? What negative impact do you think treating it as a normal function will have?

**Comment by h13i32maru** [comment]
Sorry for late reply.
This plugin is out-of-date. Please check [using ECMAScript Proposal](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
