### ISSUE TITLE
Could this sort of static functions be documented with this plug-in

### ISSUE THREAD

**Issue by iPurpl3x** [esdoc/esdoc-es7-plugin#7]
I am using react and to be able to have custom methods in a react class, they have to be binded. My solution here was to use this syntax : 

```
export default class Comp extends React.Component {
    /**
     * Desc
     * @param {Object} param- Desc
     */
    static func= (param) => {
        return
    };
}
```

Sadly there is no doc output for this. 

Could this be fixed ?

**Comment by pixelass** [comment]
I think methods are not generated either.

``` js
export const Foo = createClass({
  /**
   * @param {object} someParam - this is just a demo param
   */
  someMethod(someParam){}
})
```

not sure if it works with ES6 classes

**Comment by h13i32maru** [comment]
Sorry for late reply.
This plugin is out-of-date. Please check [using ECMAScript Proposal](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
