### ISSUE TITLE
ES7 Decorators in @example

### ISSUE THREAD

**Issue by mkxml** [esdoc/esdoc-es7-plugin#8]
Hello.

I really appreciate the efforts behind `esdoc` and this plugin.

My current problem is that I can't use decorators inside an `@example`.

It thinks it is another annotation and stops the documentation.

Snippet tested:

``` javascript
/**
 * Enhances the component with pure render functionality
 * @public
 * @example
 * // Usage as a component decorator
 * @withPureRender <-- Here is the problem, here it stops parsing
 * class MyComponent extends React.Component {
 *  render() { return <p>Hello World!</p>; }
 * }
 * @param {React.Component} PureComponent - the component to be enhanced
 * @return {React.Component} - the enhanced component
 */
```

Result: Documentation only partially generated.

`@example`s in other parts of the code work just fine when not using decorators.

**Comment by h13i32maru** [comment]
Sorry for late reply.
This plugin is out-of-date. Please check [using ECMAScript Proposal](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
