### ISSUE TITLE
Outdated Babylon - plugin can be replaced with babel-eslint parser

### ISSUE THREAD

**Issue by stevoland** [esdoc/esdoc-es7-plugin#9]
I noticed that this plugin doesn't support Flow `type` declarations as it uses an old version of Babylon. It seems babel-eslint implements a more up-to-date Babylon-to-Espree AST converter so this plugin can be replaced with:

``` javascript
var parse = require('babel-eslint').parse;

function parser(code) {
    return parse(code);
}

module.exports.onHandleCodeParser = function(ev) {
    ev.data.parser = parser;
};
```

Let me know if you want a pull request. Thanks for your libraries.

**Comment by h13i32maru** [comment]
Sorry for late reply.
This plugin is out-of-date. Please check [using ECMAScript Proposal](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
